version: '3'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my_network

  app:
    build: ./docker
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
